import React, { useState } from 'react';
import { AuthService, AuthUser } from '../services/firebaseAuth';
import { Lock, Mail, User, AlertCircle, ArrowRight, X } from 'lucide-react';

interface AuthModalProps { isOpen:boolean; onClose:()=>void; onSuccess:(user:AuthUser)=>void; initialMode?:'signin'|'signup'; }
export const AuthModal:React.FC<AuthModalProps>=({isOpen,onClose,onSuccess,initialMode='signin'})=>{
  const [mode,setMode]=useState<'signin'|'signup'>(initialMode); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  if(!isOpen)return null;
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!email||!password){setError('Email and password are required.');return;}if(password.length<6){setError('Password must be at least 6 characters.');return;}setLoading(true);try{const user=mode==='signup'?await AuthService.signUp(email,password,name.trim()):await AuthService.signIn(email,password);onSuccess(user);onClose();}catch(err){setError(err instanceof Error?err.message:'Authentication failed.');}finally{setLoading(false);}};
  return <div className="fixed inset-0 z-50 bg-[#050505]/90 backdrop-blur-md flex items-center justify-center p-4"><div className="bg-[#0a0a0a] border border-zinc-800 w-full max-w-md p-8 relative shadow-2xl rounded-2xl"><button onClick={onClose} className="absolute top-6 right-6 text-zinc-500 hover:text-white"><X className="w-5 h-5"/></button><div className="mb-6"><div className="text-xs font-mono font-bold tracking-widest text-yellow-400 uppercase">{mode==='signup'?'Create your account':'Account sign in'}</div><h2 className="text-3xl font-display font-black text-white mt-2">{mode==='signup'?'JOIN SLAM':'WELCOME BACK'}</h2><p className="text-xs text-zinc-500 mt-2">Your career profile and application history are tied to your account.</p></div>{error&&<div className="mb-4 p-3 bg-red-950/40 border border-red-800/60 rounded-lg text-red-300 text-xs flex gap-2"><AlertCircle className="w-4 h-4 shrink-0"/>{error}</div>}<form onSubmit={submit} className="space-y-4">{mode==='signup'&&<div><label className="block text-xs text-zinc-400 mb-1">Full name</label><div className="relative"><User className="w-4 h-4 text-zinc-500 absolute left-3 top-3"/><input required value={name} onChange={e=>setName(e.target.value)} className="w-full bg-zinc-950 border border-zinc-800 rounded-lg pl-9 pr-3 py-2.5 text-sm text-white focus:outline-none focus:border-yellow-400" placeholder="Your name"/></div></div>}<div><label className="block text-xs text-zinc-400 mb-1">Email</label><div className="relative"><Mail className="w-4 h-4 text-zinc-500 absolute left-3 top-3"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full bg-zinc-950 border border-zinc-800 rounded-lg pl-9 pr-3 py-2.5 text-sm text-white focus:outline-none focus:border-yellow-400" placeholder="name@example.com"/></div></div><div><label className="block text-xs text-zinc-400 mb-1">Password</label><div className="relative"><Lock className="w-4 h-4 text-zinc-500 absolute left-3 top-3"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full bg-zinc-950 border border-zinc-800 rounded-lg pl-9 pr-3 py-2.5 text-sm text-white focus:outline-none focus:border-yellow-400" placeholder="At least 6 characters"/></div></div><button disabled={loading} className="w-full py-3 bg-yellow-400 hover:bg-yellow-300 disabled:opacity-50 text-black font-black text-xs uppercase tracking-wider rounded-lg flex items-center justify-center gap-2">{loading?'PROCESSING':mode==='signup'?'CREATE ACCOUNT':'SIGN IN'}<ArrowRight className="w-4 h-4"/></button></form><button type="button" onClick={()=>{setMode(mode==='signup'?'signin':'signup');setError('');}} className="w-full mt-5 pt-4 border-t border-zinc-900 text-xs text-zinc-400 hover:text-white">{mode==='signup'?<>Already have an account? <b className="text-yellow-400">Sign in</b></>:<>New to SLAM? <b className="text-yellow-400">Create an account</b></>}</button></div></div>;
};
