import React, { useState } from 'react';
import { UserProfile } from '../types';
import { ResumeImporter } from './ResumeImporter';
import { ArrowLeft, ArrowRight, CheckCircle2, Plus, ShieldCheck, Sparkles, X } from 'lucide-react';

interface Props { userProfile: UserProfile; setUserProfile: React.Dispatch<React.SetStateAction<UserProfile>>; onComplete: () => void; }

export const OnboardingFlow: React.FC<Props> = ({ userProfile, setUserProfile, onComplete }) => {
  const [step, setStep] = useState(1);
  const [newSkill, setNewSkill] = useState('');
  const [newRole, setNewRole] = useState('');

  const update = (patch: Partial<UserProfile>) => setUserProfile((prev) => ({ ...prev, ...patch }));
  const addSkill = () => { const value = newSkill.trim(); if (!value || userProfile.skills.includes(value)) return; update({ skills: [...userProfile.skills, value] }); setNewSkill(''); };
  const addRole = () => { const value = newRole.trim(); if (!value || userProfile.targetRoles.includes(value)) return; update({ targetRoles: [...userProfile.targetRoles, value] }); setNewRole(''); };
  const valid = Boolean(userProfile.name.trim() && userProfile.country.trim() && (userProfile.skills.length > 0 || userProfile.targetRoles.length > 0));

  return <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
    <div className="flex items-center justify-between max-w-xl mx-auto mb-10">
      {[['1','Resume'],['2','Verify'],['3','Preferences']].map(([num,label]) => <div key={num} className="flex flex-col items-center"><div className={`w-9 h-9 rounded-full flex items-center justify-center font-mono text-xs font-bold ${step === Number(num) ? 'bg-yellow-400 text-black ring-4 ring-yellow-400/20' : step > Number(num) ? 'bg-emerald-500 text-white' : 'bg-zinc-800 text-zinc-500'}`}>{step > Number(num) ? <CheckCircle2 className="w-5 h-5" /> : num}</div><span className={`text-[11px] font-mono mt-2 uppercase tracking-wider ${step === Number(num) ? 'text-white font-bold' : 'text-zinc-500'}`}>{label}</span></div>)}
    </div>

    {step === 1 && <div><ResumeImporter onProfile={(profile) => { setUserProfile((prev) => ({ ...prev, ...profile })); setStep(2); }} /><div className="text-center mt-6"><button onClick={() => setStep(2)} className="text-xs text-zinc-500 hover:text-zinc-300 underline font-mono">Skip resume upload and enter profile manually →</button></div></div>}

    {step === 2 && <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 sm:p-8 space-y-6">
      <div className="border-b border-zinc-800 pb-4"><div className="text-xs font-mono uppercase tracking-widest text-yellow-400 font-bold">Step 2 of 3</div><h2 className="text-3xl font-display font-black text-white mt-1">VERIFY YOUR FACTS.</h2><p className="text-xs text-zinc-400 mt-1">Anything missing stays missing. Edit only what is actually true about you.</p></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <label className="text-xs text-zinc-400">Full Name<input value={userProfile.name} onChange={(e) => update({ name: e.target.value })} placeholder="Your full name" className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-yellow-400" /></label>
        <label className="text-xs text-zinc-400">Email<input type="email" value={userProfile.email} onChange={(e) => update({ email: e.target.value })} placeholder="name@example.com" className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-yellow-400" /></label>
        <label className="text-xs text-zinc-400">Country / Market<input value={userProfile.country} onChange={(e) => update({ country: e.target.value })} placeholder="India, United States, Germany…" className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-yellow-400" /></label>
        <label className="text-xs text-zinc-400">Years of Experience<input type="number" min={0} max={60} value={userProfile.yearsOfExperience} onChange={(e) => update({ yearsOfExperience: Math.max(0, Number(e.target.value) || 0) })} className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-yellow-400" /></label>
      </div>
      <label className="block text-xs text-zinc-400">Professional Headline<input value={userProfile.headline} onChange={(e) => update({ headline: e.target.value })} placeholder="Only add a headline that accurately describes you" className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-yellow-400" /></label>
      <div><div className="text-xs font-medium text-zinc-400 mb-2">Skills ({userProfile.skills.length})</div><div className="flex flex-wrap gap-2 mb-3">{userProfile.skills.map((skill) => <span key={skill} className="px-2.5 py-1 bg-zinc-800 border border-zinc-700 text-xs text-zinc-200 rounded-full flex items-center gap-1.5">{skill}<button type="button" onClick={() => update({ skills: userProfile.skills.filter((x) => x !== skill) })} className="text-zinc-500 hover:text-red-400"><X className="w-3 h-3" /></button></span>)}</div><div className="flex gap-2 max-w-sm"><input value={newSkill} onChange={(e) => setNewSkill(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), addSkill())} placeholder="Add a real skill" className="flex-1 bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-1.5 text-xs text-white focus:outline-none focus:border-yellow-400" /><button type="button" onClick={addSkill} className="px-3 py-1.5 bg-zinc-800 text-xs font-bold text-white rounded-lg border border-zinc-700 flex items-center gap-1"><Plus className="w-3 h-3" />Add</button></div></div>
      <div className="flex items-center justify-between pt-5 border-t border-zinc-800"><button type="button" onClick={() => setStep(1)} className="px-4 py-2 text-xs font-bold text-zinc-400 hover:text-white flex items-center gap-1.5"><ArrowLeft className="w-4 h-4" />Back</button><button type="button" onClick={() => setStep(3)} disabled={!userProfile.name.trim() || !userProfile.country.trim()} className="px-6 py-2.5 bg-yellow-400 disabled:opacity-40 text-black text-xs font-black uppercase rounded-lg flex items-center gap-2">Continue<ArrowRight className="w-4 h-4" /></button></div>
    </div>}

    {step === 3 && <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 sm:p-8 space-y-6">
      <div className="border-b border-zinc-800 pb-4"><div className="text-xs font-mono uppercase tracking-widest text-yellow-400 font-bold">Step 3 of 3</div><h2 className="text-3xl font-display font-black text-white mt-1">SET REAL SEARCH TARGETS.</h2><p className="text-xs text-zinc-400 mt-1">SLAM will not invent target roles for you. Add the roles you actually want.</p></div>
      <div><div className="text-xs font-medium text-zinc-400 mb-2">Target Roles ({userProfile.targetRoles.length})</div><div className="flex flex-wrap gap-2 mb-3">{userProfile.targetRoles.map((role) => <span key={role} className="px-3 py-1 bg-zinc-800 border border-zinc-700 text-xs text-white rounded-md flex items-center gap-2">{role}<button type="button" onClick={() => update({ targetRoles: userProfile.targetRoles.filter((x) => x !== role) })} className="text-zinc-500 hover:text-red-400"><X className="w-3 h-3" /></button></span>)}</div><div className="flex gap-2 max-w-md"><input value={newRole} onChange={(e) => setNewRole(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), addRole())} placeholder="e.g. Backend Engineer" className="flex-1 bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-yellow-400" /><button type="button" onClick={addRole} className="px-3 py-2 bg-zinc-800 text-xs font-bold text-white rounded-lg border border-zinc-700 flex items-center gap-1"><Plus className="w-3 h-3" />Add role</button></div></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="text-xs text-zinc-400">Work Arrangement<select value={userProfile.relocationPreference} onChange={(e) => update({ relocationPreference: e.target.value as any })} className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-xs text-white"><option value="Remote Only">Remote Only</option><option value="No">Hybrid / Local Preferred</option><option value="Yes">Open to Relocation</option></select></label><label className="text-xs text-zinc-400">Work Authorization<select value={userProfile.workAuth} onChange={(e) => update({ workAuth: e.target.value as any })} className="mt-1 w-full bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-xs text-white"><option value="Unknown">Not Specified</option><option value="Authorized">Authorized to work</option><option value="Needs Sponsorship">Requires Visa Sponsorship</option><option value="Citizen/PR">Citizen / Permanent Resident</option></select></label></div>
      <div className="p-4 bg-zinc-950 border border-zinc-800 rounded-xl flex items-start gap-3"><ShieldCheck className="w-5 h-5 text-yellow-400 shrink-0" /><div className="text-xs text-zinc-400"><b className="text-white">Live discovery:</b> current production discovery uses a verified public job feed. Additional sources appear only when an official connector is actually enabled.</div></div>
      {!valid && <div className="text-xs text-amber-300 border border-amber-900/60 bg-amber-950/20 rounded-lg p-3">Add at least one real skill or target role before launching discovery.</div>}
      <div className="flex items-center justify-between pt-5 border-t border-zinc-800"><button type="button" onClick={() => setStep(2)} className="px-4 py-2 text-xs font-bold text-zinc-400 hover:text-white flex items-center gap-1.5"><ArrowLeft className="w-4 h-4" />Back</button><button type="button" onClick={onComplete} disabled={!valid} className="px-6 py-2.5 bg-yellow-400 disabled:opacity-40 text-black text-xs font-black uppercase rounded-lg flex items-center gap-2"><Sparkles className="w-4 h-4" />Launch Live Discovery</button></div>
    </div>}
  </div>;
};
