import { UserProfile, JobPreference, JobPosting, ApplicationAnswer, ApplicationRecord } from './types';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: "Alex Morgan",
  email: "alex.morgan.dev@gmail.com",
  phone: "+1 (415) 890-4321",
  location: "San Francisco, CA",
  country: "United States",
  timezone: "PST (UTC-8)",
  headline: "Senior Full-Stack & Frontend Engineer (React / TypeScript / Node.js / Python)",
  summary: "Results-driven software engineer with 5+ years of experience architecting resilient web applications, developer platforms, and high-throughput microservices. Deep expertise in modern React, TypeScript, distributed systems, and cloud architecture.",
  yearsOfExperience: 5,
  currentRole: "Senior Frontend Engineer",
  targetRoles: ["Senior Frontend Engineer", "Staff Software Engineer", "Full Stack Engineer", "UI Systems Architect"],
  industries: ["Developer Tools", "Cloud Infrastructure", "Fintech", "Enterprise SaaS"],
  skills: [
    "React", "TypeScript", "JavaScript", "Next.js", "Node.js", "Python", "FastAPI",
    "PostgreSQL", "Tailwind CSS", "GraphQL", "REST APIs", "Docker", "AWS", "Git",
    "System Design", "Microfrontends", "CI/CD", "WebSockets"
  ],
  technologies: ["Vite", "Turborepo", "Prisma", "Redis", "Jest", "Playwright", "GitHub Actions", "Terraform"],
  certifications: ["AWS Certified Solutions Architect - Associate", "Meta Certified Front-End Developer"],
  education: [
    {
      id: "edu-1",
      institution: "University of California, Berkeley",
      degree: "Bachelor of Science",
      fieldOfStudy: "Computer Science",
      graduationYear: "2020",
    }
  ],
  workHistory: [
    {
      id: "exp-1",
      company: "Veloce Cloud Systems",
      role: "Senior Software Engineer",
      startDate: "2022-03",
      endDate: "Present",
      isCurrent: true,
      location: "San Francisco, CA (Hybrid)",
      bullets: [
        "Architected core dashboard UI serving 140k+ monthly active developers with sub-150ms interaction latency.",
        "Engineered real-time telemetry streaming pipeline using WebSockets and React Virtualization, reducing memory usage by 42%.",
        "Mentored 6 junior/mid-level engineers and established TypeScript strictness standards across 14 micro-repositories."
      ],
    },
    {
      id: "exp-2",
      company: "Apex Labs Inc.",
      role: "Full Stack Engineer",
      startDate: "2020-06",
      endDate: "2022-02",
      isCurrent: false,
      location: "Remote",
      bullets: [
        "Designed and shipped customer-facing billing & onboarding microservices in Python FastAPI and Node.js.",
        "Integrated multi-tenant Stripe subscription billing and Automated Webhook reconciliation.",
        "Spearheaded redesign of component design system with 100% WCAG 2.1 AA accessibility compliance."
      ],
    }
  ],
  languages: ["English (Native)", "Spanish (Conversational)"],
  workAuth: "Authorized",
  sponsorshipRequired: false,
  noticePeriod: "2 Weeks",
  availability: "Immediate after standard notice",
  relocationPreference: "No",
  salaryExpectation: "$155,000 - $185,000 USD",
};

export const INITIAL_JOB_PREFERENCES: JobPreference = {
  desiredRoles: ["Senior Frontend Engineer", "Staff Software Engineer", "Full Stack Engineer"],
  locations: ["San Francisco, CA", "Remote", "Seattle, WA", "New York, NY"],
  remotePreference: "Any",
  employmentTypes: ["Full-time"],
  minSalary: 140000,
  maxSalary: 200000,
  experienceLevel: "Senior",
  excludedCompanies: ["CryptoCasino Ltd", "Revive Spam Media"],
  excludedKeywords: ["WordPress", "PHP 5", "On-call 24/7 unpaid"],
  requiredKeywords: ["TypeScript", "React"],
};

export const INITIAL_ANSWER_LIBRARY: ApplicationAnswer[] = [
  {
    id: "ans-1",
    question: "Are you legally authorized to work in the United States?",
    normalizedQuestion: "work_authorization_us",
    answer: "Yes, I am a US Citizen and legally authorized to work in the United States without any restriction.",
    source: "User-Approved",
    isApproved: true,
    lastUpdated: "2026-08-15",
    category: "Authorization",
  },
  {
    id: "ans-2",
    question: "Will you now or in the future require sponsorship for employment visa status?",
    normalizedQuestion: "sponsorship_requirement",
    answer: "No, I do not and will not require sponsorship for employment visa status.",
    source: "User-Approved",
    isApproved: true,
    lastUpdated: "2026-08-15",
    category: "Authorization",
  },
  {
    id: "ans-3",
    question: "What is your target annual salary expectation?",
    normalizedQuestion: "salary_expectation",
    answer: "$165,000 - $185,000 base salary, open to discussing total compensation including equity and benefits.",
    source: "User-Approved",
    isApproved: true,
    lastUpdated: "2026-08-20",
    category: "Compensation",
  },
  {
    id: "ans-4",
    question: "What is your earliest available start date / notice period?",
    normalizedQuestion: "notice_period_availability",
    answer: "I can start within two weeks of receiving an offer to ensure a clean handover with my current team.",
    source: "User-Approved",
    isApproved: true,
    lastUpdated: "2026-08-20",
    category: "Availability",
  },
  {
    id: "ans-5",
    question: "How many years of professional experience do you have with React and TypeScript?",
    normalizedQuestion: "react_typescript_years",
    answer: "I have over 5 years of production experience building mission-critical web applications with React and TypeScript.",
    source: "User-Approved",
    isApproved: true,
    lastUpdated: "2026-08-25",
    category: "Technical",
  },
  {
    id: "ans-6",
    question: "Why are you interested in joining our company?",
    normalizedQuestion: "why_join_company",
    answer: "I am passionate about developer enablement and building robust, high-leverage products. Your team's technical bar and product velocity strongly resonate with how I operate.",
    source: "User-Approved",
    isApproved: true,
    lastUpdated: "2026-08-28",
    category: "Behavioral",
  },
];

export const INITIAL_JOB_POSTINGS: JobPosting[] = [
  {
    id: "job-stripe-01",
    title: "Senior Frontend Engineer - Developer Dashboard",
    normalizedTitle: "Senior Frontend Engineer",
    roleFamily: "Frontend Engineering",
    company: "Stripe",
    companyDomain: "stripe.com",
    location: "San Francisco, CA / Remote",
    remote: true,
    remoteType: "Remote",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    minYearsExperience: 4,
    minSalary: 165000,
    maxSalary: 215000,
    currency: "USD",
    salaryText: "$165,000 - $215,000 USD + Equity",
    description: "Stripe is looking for a Senior Frontend Engineer to build the core interfaces millions of global businesses interact with daily. You will craft high-performance UI components, lead architecture reviews, and maintain world-class reliability.",
    responsibilities: [
      "Design and implement scalable frontend architecture in React and TypeScript.",
      "Collaborate with API teams to design high-throughput REST and GraphQL endpoints.",
      "Drive observability, test automation, and sub-100ms web vitals.",
      "Partner with product managers and designers to deliver refined user workflows."
    ],
    requirements: [
      "4+ years of professional experience in React, TypeScript, and modern CSS.",
      "Strong understanding of browser internals, performance profiling, and state management.",
      "Experience with automated testing (Jest, Playwright) and CI/CD pipelines.",
      "Demonstrated ability to mentor engineers and drive technical consensus."
    ],
    requiredSkills: ["React", "TypeScript", "GraphQL", "REST APIs", "System Design"],
    preferredSkills: ["Next.js", "Docker", "Node.js", "Tailwind CSS"],
    postingDate: "2026-08-31",
    freshnessLabel: "Posted 3 hours ago",
    lastSeenAt: "2026-09-01T07:15:00Z",
    applicationUrl: "https://stripe.com/jobs/listing/fe-dashboard-492",
    primarySource: "Company Careers (Greenhouse ATS)",
    sourcesList: [
      {
        sourceName: "Stripe Careers (Direct ATS)",
        sourceUrl: "https://stripe.com/jobs/listing/fe-dashboard-492",
        sourceType: "Direct ATS",
        postedDate: "2026-08-31",
        isOfficial: true,
      },
      {
        sourceName: "LinkedIn Job Listing",
        sourceUrl: "https://linkedin.com/jobs/view/401928371",
        sourceType: "Job Board",
        postedDate: "2026-08-31",
        isOfficial: false,
      },
      {
        sourceName: "Google Jobs Aggregator",
        sourceUrl: "https://google.com/search?q=stripe+senior+frontend+engineer",
        sourceType: "Aggregator",
        postedDate: "2026-08-31",
        isOfficial: false,
      }
    ],
    applicationMethod: "Direct ATS",
    recruiterName: "Sarah Jenkins (Technical Recruiting Lead)",
    recruiterEmail: "sjenkins@stripe.com",
    applicantCount: "42 applicants",
    hardRequirements: ["4+ years software engineering experience", "Authorized to work in US or Remote-eligible timezone"],
    requiresWorkAuth: true,
  },
  {
    id: "job-linear-02",
    title: "Product Engineer (Web & Desktop)",
    normalizedTitle: "Full Stack / Frontend Engineer",
    roleFamily: "Product Engineering",
    company: "Linear",
    companyDomain: "linear.app",
    location: "San Francisco, CA / Remote",
    remote: true,
    remoteType: "Remote",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    minYearsExperience: 4,
    minSalary: 160000,
    maxSalary: 200000,
    currency: "USD",
    salaryText: "$160,000 - $200,000 USD + Top 0.1% Equity",
    description: "Linear is seeking an exceptional product-minded engineer to build lightning-fast web and desktop experiences. We obsess over milliseconds, fluid keyboard navigation, and delightful micro-interactions.",
    responsibilities: [
      "Build fluid, instantaneous web applications using React, TypeScript, and custom local-first sync engines.",
      "Work closely with founders on end-to-end product architecture and execution.",
      "Maintain zero-compromise aesthetic standards and robust offline persistence."
    ],
    requirements: [
      "Proven track record building polished, high-performance web applications.",
      "Mastery of TypeScript, modern React, state synchronization, and DOM layout mechanics.",
      "Strong sense of visual hierarchy, ergonomics, and typography."
    ],
    requiredSkills: ["React", "TypeScript", "WebSockets", "Node.js", "System Design"],
    preferredSkills: ["FastAPI", "Python", "Tailwind CSS", "Electron"],
    postingDate: "2026-08-30",
    freshnessLabel: "Posted yesterday",
    lastSeenAt: "2026-09-01T06:40:00Z",
    applicationUrl: "https://linear.app/careers/product-engineer",
    primarySource: "Company Careers (Ashby ATS)",
    sourcesList: [
      {
        sourceName: "Linear Official Portal",
        sourceUrl: "https://linear.app/careers/product-engineer",
        sourceType: "Direct ATS",
        postedDate: "2026-08-30",
        isOfficial: true,
      },
      {
        sourceName: "Hacker News Who Is Hiring",
        sourceUrl: "https://news.ycombinator.com/item?id=413982",
        sourceType: "Company Page",
        postedDate: "2026-08-30",
        isOfficial: true,
      }
    ],
    applicationMethod: "Direct ATS",
    recruiterName: "Karri Saarinen (Head of Product)",
    recruiterEmail: "careers@linear.app",
    applicantCount: "18 applicants",
    hardRequirements: ["Demonstrated portfolio of production web applications", "Fluent in English"],
    requiresWorkAuth: false,
  },
  {
    id: "job-datadog-03",
    title: "Senior Full Stack Engineer - Cloud Monitoring",
    normalizedTitle: "Senior Full Stack Engineer",
    roleFamily: "Full Stack Engineering",
    company: "Datadog",
    companyDomain: "datadoghq.com",
    location: "New York, NY / Hybrid",
    remote: false,
    remoteType: "Hybrid",
    employmentType: "Full-time",
    experienceLevel: "Senior",
    minYearsExperience: 5,
    minSalary: 170000,
    maxSalary: 220000,
    currency: "USD",
    salaryText: "$170,000 - $220,000 USD",
    description: "Datadog is looking for a Senior Full Stack Engineer to build visualization engines for billions of real-time telemetry metrics. You will develop backend data pipelines in Python/Go and high-density interactive visualizers in TypeScript.",
    responsibilities: [
      "Develop reliable microservices and scalable REST/gRPC endpoints.",
      "Build complex interactive canvas and chart components with TypeScript and D3.",
      "Optimize query performance across distributed database clusters."
    ],
    requirements: [
      "5+ years building full-stack applications with TypeScript and Python or Go.",
      "Experience with PostgreSQL, Redis, Docker, and distributed computing.",
      "Deep understanding of distributed systems and telemetry visualization."
    ],
    requiredSkills: ["TypeScript", "Python", "FastAPI", "PostgreSQL", "Docker", "React"],
    preferredSkills: ["AWS", "Kubernetes", "GraphQL", "CI/CD"],
    postingDate: "2026-08-28",
    freshnessLabel: "Posted 4 days ago",
    lastSeenAt: "2026-09-01T04:20:00Z",
    applicationUrl: "https://careers.datadoghq.com/detail/5839211",
    primarySource: "Datadog Careers (Workday ATS)",
    sourcesList: [
      {
        sourceName: "Datadog Careers (Workday)",
        sourceUrl: "https://careers.datadoghq.com/detail/5839211",
        sourceType: "Direct ATS",
        postedDate: "2026-08-28",
        isOfficial: true,
      },
      {
        sourceName: "Indeed Verified Listing",
        sourceUrl: "https://indeed.com/viewjob?jk=8391823901",
        sourceType: "Job Board",
        postedDate: "2026-08-28",
        isOfficial: false,
      }
    ],
    applicationMethod: "Supported Automation",
    recruiterName: "Marcus Vance (Senior Engineering Recruiter)",
    recruiterEmail: "mvance@datadoghq.com",
    applicantCount: "87 applicants",
    hardRequirements: ["5+ years experience", "Ability to work hybrid in NYC office 2 days/week"],
    requiresWorkAuth: true,
  },
  {
    id: "job-cloudflare-04",
    title: "Staff Software Engineer - Developer Platform",
    normalizedTitle: "Staff Software Engineer",
    roleFamily: "Platform Engineering",
    company: "Cloudflare",
    companyDomain: "cloudflare.com",
    location: "San Francisco, CA / Remote",
    remote: true,
    remoteType: "Remote",
    employmentType: "Full-time",
    experienceLevel: "Lead / Staff",
    minYearsExperience: 7,
    minSalary: 190000,
    maxSalary: 245000,
    currency: "USD",
    salaryText: "$190,000 - $245,000 USD + RSUs",
    description: "Join Cloudflare Workers team to build the next generation of global edge compute APIs and developer portals. We are empowering millions of engineers to run code at the edge in over 300 cities worldwide.",
    responsibilities: [
      "Architect developer portals, CLI integrations, and edge compute services.",
      "Lead cross-team technical initiatives across security, compute, and networking.",
      "Author RFCs and champion architectural standards."
    ],
    requirements: [
      "7+ years experience with high-scale distributed systems and web architectures.",
      "Deep expertise in TypeScript, Rust, or Python with distributed edge primitives.",
      "Exceptional systems design capability and RFC authorship track record."
    ],
    requiredSkills: ["TypeScript", "System Design", "Docker", "Node.js", "Python", "CI/CD"],
    preferredSkills: ["Rust", "Kubernetes", "WebSockets"],
    postingDate: "2026-08-25",
    freshnessLabel: "Posted 6 days ago",
    lastSeenAt: "2026-08-31T18:00:00Z",
    applicationUrl: "https://cloudflare.com/careers/jobs/staff-eng-9382",
    primarySource: "Cloudflare Careers (Lever ATS)",
    sourcesList: [
      {
        sourceName: "Cloudflare Lever Portal",
        sourceUrl: "https://cloudflare.com/careers/jobs/staff-eng-9382",
        sourceType: "Direct ATS",
        postedDate: "2026-08-25",
        isOfficial: true,
      }
    ],
    applicationMethod: "Direct ATS",
    recruiterName: "Elena Rostova (Staff Talent Partner)",
    recruiterEmail: "erostova@cloudflare.com",
    applicantCount: "112 applicants",
    hardRequirements: ["7+ years systems experience", "US Citizenship or Green Card for government edge compliance"],
    requiresWorkAuth: true,
  },
  {
    id: "job-figma-05",
    title: "Software Engineer - Design Systems & Web UI",
    normalizedTitle: "Frontend / Design Systems Engineer",
    roleFamily: "Design Systems",
    company: "Figma",
    companyDomain: "figma.com",
    location: "San Francisco, CA / Remote",
    remote: true,
    remoteType: "Remote",
    employmentType: "Full-time",
    experienceLevel: "Mid-Senior",
    minYearsExperience: 3,
    minSalary: 155000,
    maxSalary: 195000,
    currency: "USD",
    salaryText: "$155,000 - $195,000 USD",
    description: "Figma is seeking an engineer passionate about design systems, accessible components, and developer tooling to build internal and external UI libraries powering the collaborative design platform.",
    responsibilities: [
      "Develop reusable component libraries in React and TypeScript with rigorous accessibility standards.",
      "Work closely with design leads to bridge token synchronization between Figma and code.",
      "Optimize bundle size, rendering performance, and developer ergonomics."
    ],
    requirements: [
      "3+ years experience with modern React, TypeScript, and CSS architecture.",
      "Deep understanding of accessibility guidelines (WAI-ARIA, WCAG 2.1).",
      "Passion for typography, layout, and component-driven architecture."
    ],
    requiredSkills: ["React", "TypeScript", "Tailwind CSS", "REST APIs"],
    preferredSkills: ["Next.js", "GraphQL", "Jest", "Microfrontends"],
    postingDate: "2026-09-01",
    freshnessLabel: "Posted 1 hour ago",
    lastSeenAt: "2026-09-01T07:05:00Z",
    applicationUrl: "https://figma.com/careers/design-systems-eng-21",
    primarySource: "Figma Careers (Greenhouse ATS)",
    sourcesList: [
      {
        sourceName: "Figma Careers (Greenhouse)",
        sourceUrl: "https://figma.com/careers/design-systems-eng-21",
        sourceType: "Direct ATS",
        postedDate: "2026-09-01",
        isOfficial: true,
      },
      {
        sourceName: "LinkedIn Easy Apply Sync",
        sourceUrl: "https://linkedin.com/jobs/view/figma-design-systems",
        sourceType: "Job Board",
        postedDate: "2026-09-01",
        isOfficial: false,
      }
    ],
    applicationMethod: "Direct ATS",
    recruiterName: "Dave Chen (Senior Technical Recruiter)",
    recruiterEmail: "dchen@figma.com",
    applicantCount: "14 applicants",
    hardRequirements: ["3+ years frontend experience", "Portfolio or code sample demonstrating UI engineering"],
    requiresWorkAuth: false,
  }
];

export const INITIAL_APPLICATION_RECORDS: ApplicationRecord[] = [
  {
    id: "app-rec-01",
    jobId: "job-stripe-01",
    jobTitle: "Senior Frontend Engineer - Developer Dashboard",
    company: "Stripe",
    location: "San Francisco, CA / Remote",
    salaryText: "$165,000 - $215,000 USD + Equity",
    dateDiscovered: "2026-08-31",
    dateApplied: "2026-08-31",
    status: "APPLIED",
    compatibilityScore: 94,
    applicationMode: "REVIEW",
    resumeVersionUsed: "Tailored Resume v1 (Stripe Focus)",
    coverLetter: "Dear Stripe Hiring Team, I am writing to express my enthusiastic interest in the Senior Frontend Engineer position...",
    submittedAnswers: [
      { question: "Work Authorization", answer: "Authorized to work in US without sponsorship" },
      { question: "Notice Period", answer: "2 Weeks" }
    ],
    notes: "Applied directly through official Greenhouse portal with tailored resume emphasizing sub-150ms latency metrics.",
    applicationUrl: "https://stripe.com/jobs/listing/fe-dashboard-492",
    source: "Company Careers (Greenhouse ATS)",
    lastUpdated: "2026-08-31T20:15:00Z",
  },
  {
    id: "app-rec-02",
    jobId: "job-linear-02",
    jobTitle: "Product Engineer (Web & Desktop)",
    company: "Linear",
    location: "San Francisco, CA / Remote",
    salaryText: "$160,000 - $200,000 USD + Top 0.1% Equity",
    dateDiscovered: "2026-08-30",
    dateApplied: "2026-08-30",
    status: "INTERVIEW",
    compatibilityScore: 92,
    applicationMode: "ASSISTED",
    resumeVersionUsed: "Tailored Resume v2 (Linear Product Focus)",
    coverLetter: "Dear Linear Team, I have long admired Linear's obsession with speed and micro-interactions...",
    submittedAnswers: [
      { question: "Why Linear?", answer: "Passionate about building fast, keyboard-first developer tools." }
    ],
    notes: "Recruiter reached out for initial 30-min technical conversation scheduled for Thursday.",
    applicationUrl: "https://linear.app/careers/product-engineer",
    source: "Company Careers (Ashby ATS)",
    lastUpdated: "2026-09-01T06:00:00Z",
  }
];
